version: 2.1
jobs:
  build_and_test:
    parameters:
      compiler:
        description: C++ compiler to build with
        type: string
      standard:
        description: C++ standard to build with
        type: string
      mode:
        description: mode to build and test with
        type: string
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: sudo ./install-dependencies.sh << parameters.compiler >> << parameters.standard >> << parameters.mode >>

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: circleci-project-setup
          matrix:
            parameters:
              compiler: ["clang++-12"]
              standard: ["20"]
              mode: ["dev"]
